./run will not execute jar if compile fails

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,2 +1,5 @@
 ant compile jar
+if [[ "$?" -ne 0 ]] ; then
+  echo 'could not build. exiting'; exit $rc
+fi
 java -jar build/jar/Holon.jar
